spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_test
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: create-drop